version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: randompassword
      POSTGRES_USER: johndoe
      POSTGRES_User: johndoe
      POSTGRES_DB: mydb
    ports:
      - 5432:5432